
#ifndef TES_BANK_SRC_ACCOUNT_TASK_FETCHBALANCETASK_HPP
#define TES_BANK_SRC_ACCOUNT_TASK_FETCHBALANCETASK_HPP
class FetchBalanceTask : public AsyncTaskBase {

};


#endif  // TES_BANK_SRC_ACCOUNT_TASK_FETCHBALANCETASK_HPP
