name: cpplint
on: [push, pull_request]
jobs:
  cpplint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
      - run: pip install cpplint
      - run: cpplint  --linelength=120 --exclude=src/*/version.h --filter=-legal/copyright,-whitespace/indent,-readability/namespace,-build/include_subdir --recursive . 
